SDKS-3395 - Align naming and errors for Davinci
ForgeRock/unified-sdk-ios pull request #4
Opened 2024-10-04 19:15 UTC by jeyanthanperiyasamy

# JIRA Ticket

[JIRA](https://bugster.forgerock.org/jira/browse/SDKS-xxx) "Jira ticket title..."

# Description

Briefly describe the change and any information that would help speedup the review and testing process.

# Checklist:

- [ ] I ran all unit tests and they pass
- [ ] I added test case coverage for my changes

2024-10-07 16:47 UTC, witrisna commented on PingDavinci/PingDavinci/module/Transform.swift
>      }
Consider error when server return 2XX?

2024-10-07 16:48 UTC, witrisna commented on PingDavinci/PingDavinci/module/Transform.swift
> +      collectors.append(contentsOf: Form.parse(json: json))
Consider failed when return code 2XX?

2024-10-07 16:49 UTC, witrisna reviewed
Minor change

2024-10-07 16:59 UTC, witrisna commented on PingDavinci/PingDavinci/module/Transform.swift
> +      return FailureNode(cause: ApiError.error(status, json, message))
Consider failed when return code 2XX?

2024-10-10 15:30 UTC, vahancouver requested changes
Overall looks good, some minor comments

2024-10-10 15:30 UTC, vahancouver commented on PingDavinci/PingDavinci/Constants.swift
> +  static let codeNumber = 1999
can the name reflect the value? _code_1999_ or something like that

2024-10-10 15:30 UTC, vahancouver commented on PingDavinci/PingDavinci/Constants.swift
> +  static let pingOneAuthConnector = "pingOneAuthenticationConnector"
to be consistent, I'd suggest to name the variable exactly like the value where possible to avoid any duplicates or confusion later.

2024-10-14 19:53 UTC, jeyanthanperiyasamy commented
All comments addressed

2024-10-15 22:06 UTC, rodrigoareis approved these changes
Changes looks good to me

2024-10-15 23:57 UTC, spetrov requested changes
Can you also update the [README.md](https://github.com/ForgeRock/unified-sdk-ios/tree/SDKS-3395/PingDavinci/README.md) file with the new names...?

2024-10-16 14:59 UTC, vahancouver requested changes
Code changes look good. However we need to update the 
README file for DaVinci module to reflect the new names.

2024-10-16 15:27 UTC, jeyanthanperiyasamy commented
updated read me

2024-10-16 15:36 UTC, spetrov approved these changes

2024-10-16 16:12 UTC, merged